### ISSUE TITLE
Implement checks on Programs

### ISSUE THREAD

**Issue by aochagavia** [aochagavia/AFP-Ants#5]
We need to check the following properties (see `Language.Fragment.hs` at the bottom):
* All gotos target existing labels. Possible implementation: collect all goto targets into a set, collect all labels into a set, take the difference between gotos and labels (it should be empty)
* There is no dead code (eventually, we can pass a flag to allow it). It would be great to mention which labels are dead. Possible implementation: collect all gotos into a set, collect all labels into a set, take the difference between labels and gotos (it should be empty).
* There are no unused labels (ie labels without a corresponding fragment). Possible implementation: make an ordered list from the labels attached to each fragment, check if there are gaps between them (e.g. in [0, 1, 2, 5] we can see that labels 3 and 4 have been declared but don't have a corresponding fragment)

**Comment by ReinierMaas** [comment]
Create sets.
 - [ ]  Collect all gotos into a set
 - [ ]  Collect all labels into a set

All gotos target existing labels. 
 - [ ]  Gotos should be a subset of labels, `ERROR` otherwise. 

All labels should be used, no dead code.
 - [ ] Labels should be a subset of gotos, `WARNING` otherwise.

What is the problem with skipped labels? If we already check for the above

**Comment by aochagavia** [comment]
"Collect all labels into a set" finds the labels present in the program. The point is that unused labels aren't present in the program.

**Comment by JorritDorrestijn** [comment]
The no unused labels check is implemented in commit f61be97949e9be24e0c40a6e008cb84ac714f076.

**Comment by ReinierMaas** [comment]
Unused labels already didn't end up in the source code.

**Comment by aochagavia** [comment]
@ReinierMaas the checks are performed on the `Program` data type, before translating it to code.

**Comment by ReinierMaas** [comment]
Okay, that clears that up. Checked the code this time, with tests!

**Comment by JorritDorrestijn** [comment]
The no dead check code is implemented in commit c788dc85418c0c9ba7333da1c6593c3da33b2ef5. This led to some code duplication which I've fixed as well.

**Comment by JorritDorrestijn** [comment]
It looks like all properties are checked now, so I'm closing this issue.
